In [275]:
import pandas as pd
import numpy as np
pd.plotting.register_matplotlib_converters()
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import sklearn
print("Setup Complete")

Setup Complete


In [276]:
df_path = "/content/prosper_new.csv"

df = pd.read_csv(df_path)

In [277]:
df.head()

Unnamed: 0  ListingCategory  BorrowerState  IsBorrowerHomeowner  \
0           1                8              5                    0   
1           3               12             10                    1   
2           4                8             21                    1   
3           5                5             29                    1   
4           6                5             15                    0   

   IncomeRange  IncomeVerifiable  DebtToIncomeRatio  StatedMonthlyIncome  \
0            4                 1                 18                 6247   
1            3                 1                 15                 1955   
2            2                 1                 26                 8347   
3            2                 1                 36                 7911   
4            3                 1                 27                 1000   

   Term  ProsperRating  EmploymentStatus  LoanStatus  LoanOriginalAmount  \
0     1              0                 0           1                1104   
1     1              0                 0           1                1104   
2     1              4                 0           1                1604   
3     2              2                 0           1                1604   
4     1              5                 0           1                 198   

   BorrowerAPR  LoanStatusNew  
0          325              0  
1          375              0  
2         1383              0  
3          619              0  
4         1870              0

In [278]:
df.shape

(83982, 15)

In [279]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83982 entries, 0 to 83981
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           83982 non-null  int64
 1   ListingCategory      83982 non-null  int64
 2   BorrowerState        83982 non-null  int64
 3   IsBorrowerHomeowner  83982 non-null  int64
 4   IncomeRange          83982 non-null  int64
 5   IncomeVerifiable     83982 non-null  int64
 6   DebtToIncomeRatio    83982 non-null  int64
 7   StatedMonthlyIncome  83982 non-null  int64
 8   Term                 83982 non-null  int64
 9   ProsperRating        83982 non-null  int64
 10  EmploymentStatus     83982 non-null  int64
 11  LoanStatus           83982 non-null  int64
 12  LoanOriginalAmount   83982 non-null  int64
 13  BorrowerAPR          83982 non-null  int64
 14  LoanStatusNew        83982 non-null  int64
dtypes: int64(15)
memory usage: 9.6 MB


In [280]:
df.isnull().sum()

Unnamed: 0             0
ListingCategory        0
BorrowerState          0
IsBorrowerHomeowner    0
IncomeRange            0
IncomeVerifiable       0
DebtToIncomeRatio      0
StatedMonthlyIncome    0
Term                   0
ProsperRating          0
EmploymentStatus       0
LoanStatus             0
LoanOriginalAmount     0
BorrowerAPR            0
LoanStatusNew          0
dtype: int64

# **Regularized Logisitic Regression**

**Importing Packages**

In [281]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error,mean_absolute_error,accuracy_score,classification_report,confusion_matrix

**Splitting the Data**

In [282]:
# Split the data into features (X) and target (y)
X = df.drop('ProsperRating',axis = 1)
y = df['ProsperRating']

In [283]:
# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [284]:
# Scale the data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

**Fitting and Evaluating the Model**

In [285]:
lr = LogisticRegression(penalty='l2', C=1.0, solver='saga')

In [286]:
lr.fit(X_train, y_train)

LogisticRegression(solver='saga')

In [287]:
y_pred = lr.predict(X_test)

In [288]:
# evaluate the model
accuracy = accuracy_score(y_test, y_pred)
confusion_matrix = confusion_matrix(y_test, y_pred)

print("Accuracy:", accuracy)
print("Confusion Matrix:\n", confusion_matrix)

Accuracy: 0.7963922128951598
Confusion Matrix:
 [[2699   69  145    6    0    0    0]
 [  85 1006    2    1    0    0    0]
 [ 209    0 2408  470    1    1    0]
 [   8    0  520 2654  412    6    1]
 [   3    0   10  383 2200  226   21]
 [   0    0    1    5  301 1247  345]
 [   0    0    0   14   16  159 1163]]
